"""Add activity table

Revision ID: 04edac3a93c3
Revises: f4bdb5cec095
Create Date: 2024-12-05 10:28:58.660218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04edac3a93c3'
down_revision = 'f4bdb5cec095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
